import { Router } from 'express';
import { authMiddleware } from '../middleware/auth';
import {
  getSchedules,
  getSchedule,
  createSchedule,
  updateSchedule,
  deleteSchedule,
  getScheduleFlows,
  processRecurring,
} from '../controllers/recurring-schedule.controller';

const router = Router();

// All routes require authentication
router.use(authMiddleware);

// Process recurring schedules (run the cron job manually)
router.post('/process', processRecurring);

// CRUD routes
router.get('/', getSchedules);
router.post('/', createSchedule);
router.get('/:id', getSchedule);
router.put('/:id', updateSchedule);
router.delete('/:id', deleteSchedule);

// Get flows generated by a schedule
router.get('/:id/flows', getScheduleFlows);

export default router;
